name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build
        env:
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
